### PR TITLE
Avoid refreshing tags when loading file list

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
@tejohnso Could you review commit https://github.com/Rise-Vision/storage-client/commit/a1877c64543a073c569442e10cf696d743752a24 ? It solves an issue I was having related to Blob constructor not being found con PhantomJS. The problem is, the uploaded file does not have content, but it's still good enough to be able to tag it or trash/delete it.

**Comment by tejohnso** [comment]
What version of phantom are you using?

**Comment by fjvallarino** [comment]
1.9.7

**Comment by fjvallarino** [comment]
Added test cases for both types of tag definitions and for all three tag types of file tagging. Funny thing is one bug was found during the process :)

@tejohnso please review

**Pull request merged**
