### PR TITLE
Feature/publisher role check

### PR DESCRIPTION
**Pull request by EnlightenedCode**
this adds the client access denied modal for user role

### CODE REVIEW

**Comment by EnlightenedCode** [comment]
@fjvallarino please review. I'll probably change this to master... if ui-related-fixes goes to QA soon, but might merge it to that branch if I am still waiting for release #1 to go through. this implements these role access in the client UI https://docs.google.com/a/risevision.com/document/d/1u4QtF3ByVGo4lfdeKarXhRkkpYivGUi78V7-c_mZHOY/edit

**Comment by tejohnso** [comment]
Why is there all this client side preemptive role checking and storing of user state in an angular value?  

As per the role document[1], we aren't preemptively checking access requirements.  Let users see that there is a tag setup screen and see the tags that are set up.  When they try to change a definition, then the server will return an error, and we'll handle it like any other server error.  An i18n aware message pops up and that message will let them know of the situation.

And why is this particular use case using a modal to pop up the error ?  Do we do that elsewhere?   I've only ever seen a small div used as in the "Rise vision needs your permission" message. 
And where is the user being returned to when the modal is dismissed?  It looks like they're being thrown back into the root of the application.  

[1] https://docs.google.com/a/risevision.com/document/d/1u4QtF3ByVGo4lfdeKarXhRkkpYivGUi78V7-c_mZHOY/edit

**Comment by EnlightenedCode** [comment]
@tejohnso we can talk about this in a hangout. according the comments that I resolved. Byron wanted modals to say access denied rather than a message that would come up when the API gives a 403.  I can change it to not send them to the root but what folder they were in originally, that was unintended.

**Comment by EnlightenedCode** [comment]
@fjvallarino can you review e0f1599 and beyond? it just adds alert messages and refactors svc to give a alert error if response from API doesn't come back a 200

**Comment by fjvallarino** [comment]
:+1:

**Comment by fjvallarino** [comment]
Closing this PR since destination branch has changed

**Pull request closed without merging**
