### PR TITLE
Update In-App Selector for single and multiple files

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
@fjvallarino Here are some questions I had while going through this PR

--------

Should a service called *coreClient* be stuck in a module specific to *storage.modal*?  It sounds like *coreClient* might have more general use.

Is there a test for *coreclient*?

*loadCoreClient* returns a promise, so it shouldn't need a callback.
.then(function() {
  return loadCoreclient();
}).then(function() {
  return loadStorageClient();
}).then.......

What was the controller replaced with, in the "main.company-root" state config?

What is "My Company Storage"?

Can you describe this new header-fullscreen partial?  It looks rather large for a partial.  Should it
 be broken up?

**Comment by fjvallarino** [comment]
@tejohnso 

I agree, coreClient (now renamed CoreClientService, to follow our naming standards) should be available for the rest of the application. It has now been moved out of modal and test cases were added. Also, promise style is being used to load the apis.

The "main.company-root" controller was removed as it was done previously on fullscreen. There was no use for that controller anymore.

"My Company Storage" was part of the mockup and I was using it for testing styles in case core's company call failed. It has now been removed.

The header-fullscreen used to be part of main.html, which both fullscreen and modal share. Since modal's toolbars are now completely different, I moved those parts to a separate file which is only used by fullscreen.

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
Some old parts of modal.html were moved into the new index.html. These commits start at https://github.com/Rise-Vision/storage-client/commit/7323d819d560c4e3c2cd61ec3fab165ecc17b322

@tejohnso please review

**Pull request merged**
