### PR TITLE
Remove iframe fullscreen

### PR DESCRIPTION
**Pull request by fjvallarino**
Removed iframe, disabled Save button while waiting for Folder create confirmation and provide unencoded urls for deep linking.

@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
Updated to use html5Mode. A couple of workarounds were needed to avoid page reloads and for proper deep linking. Express is being used on dev environment instead of gulp-connect for greater flexibility (we'll need to add rules on staging and prod to return index.html when /files/* or /tagConfiguration/* is requested)

@tejohnso please review

**Comment by tejohnso** [comment]
Can you check to see if common header has a way to specify what gapi modules should be loaded?  We really shouldn't need gapi-fullscreen

**Comment by fjvallarino** [comment]
@tejohnso We can replace it with this: https://github.com/Rise-Vision/ng-gapi-loader

**Comment by tejohnso** [comment]
Looks like most others are already using it.  Let's join them.

**Comment by fjvallarino** [comment]
@tejohnso I was thinking I created gapi-fullscreen because we have cookies check set up too. Internally we are actually using ng-gapi-loader.

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
