### PR TITLE
Remove loading messages and use spinner instead

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso This is related to this issue: https://github.com/Rise-Vision/storage-client/issues/148

I tried to avoid having the spinner start and stop, but I had some issues starting the spinner while Common Header is logging in (I can't make our spinner show until CH has marked the user as authorized). Between the time the user is authorized and when the companyId is available, there is between one and two seconds. I set a timeout of 500ms before stopping a timer so we can handle sequential spinner invocations, but using 2 seconds would be overkill.

This PR starts at: https://github.com/Rise-Vision/storage-client/commit/23cf2f5c101feccfe8c82c6e12592e1eb6c07d44

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
@tejohnso please review the rebased version

**Comment by tejohnso** [comment]
Switching to a sub folder shouldn't bring up the spinner unless it takes a very long time.  Even switching to an empty sub-folder brings up the spinner and it takes less than a second.

**Comment by fjvallarino** [comment]
So only initial load should display spinner? We don't really have a way of knowing if an operation is going to take long.

**Comment by tejohnso** [comment]
Can't you do something similar as what you've done with requests to remove the spinner?  
A request to start the spinner should be queued, and only after a second or so, if the queue is not empty, it should start.

**Comment by fjvallarino** [comment]
@tejohnso Updated. Now it waits one second before first displaying the spinner.

**Comment by fjvallarino** [comment]
@tejohnso Removed task parameter and kept timers to a minimum

**Comment by tejohnso** [comment]
@fjvallarino It seemed incorrect to have the spinner continue after everything was already loaded.  Even if it was only half a second.  I removed the delay on removal but kept it on addition.  

Please review.

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
