### PR TITLE
Feature/metatag

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@tejohnso I have added a data folder with a json which contains the metadata tags. Then, a resolve on the ui-router state reads the json and set a rootScope model with the metadata. Could you please review it? You can check how it is working on https://storage-stage.risevision.com/feature-metatag/dist/?_escaped_fragment_=/

Cheers

### CODE REVIEW

**Comment by tejohnso** [comment]
What am I supposed to be seeing at 
https://storage-stage.risevision.com/feature-metatag/dist/?_escaped_fragment_=/

**Comment by rodrigopavezi** [comment]
@tejohnso if you look at the source code of https://storage-stage.risevision.com/feature-metatag/dist/?_escaped_fragment_=/, you will see that the metadata is there. Different than looking to https://storage-stage.risevision.com/feature-metatag/dist source code where you will see angular binding tags e.g. {{metatag.title}}.

Cheers

**Comment by rodrigopavezi** [comment]
@tejohnso or @fjvallarino could you please review. thanks

**Comment by fjvallarino** [comment]
@rodrigopavezi web/index.html:42 already has the ng-app attribute. Maybe one should be removed?

**Comment by rodrigopavezi** [comment]
@fjvallarino good catch. I have left the one on the html tag so the metatag model can be accessed on the head.

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
