### PR TITLE
table updates

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@EnlightenedCode make sure to update bower for the style changes to tagging. The dotdotdot directive is not working on the file name. I have added a fix for responsiveness but the dots are not showing because of this.

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@EnlightenedCode please update bower and let me know if this works,

**Comment by EnlightenedCode** [comment]
@ghislaineguerin on iphone4 it looks like this. On full screen it looks fine
image

**Comment by ghislaineguerin** [comment]
@EnlightenedCode fixed for iphone4. Update styles.

**Comment by EnlightenedCode** [comment]
:+1: merging

**Pull request merged**
